### ISSUE TITLE
CodeActionProvider doc-comment return restricts possible action kinds

### ISSUE THREAD

**Issue by lumnn** [phpactor/language-server#54]
https://github.com/phpactor/language-server/blob/323f7565b16b47bc10b5bddd88390b977cb65487/lib/Core/CodeAction/CodeActionProvider.php#L25

Documentation mentions it's an open list of a kinds, while doc-comment restricts them to the ones specified in CodeActionKind.

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionKind

**Comment by dantleech** [comment]
~probably just need to make that a string then~

**Comment by dantleech** [comment]
hm, although more of an issue with the protocol generator, it incorrectly identifies the "enum" instead of the type alias for a string.
